# Site settings
title: "Xyléan Broeders resume's"
description: "Xyléan Broeders resume's"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Xyléan Broeders"
resume_title:                   "Engeneer Student"
resume_contact_email:           "xbroeders@etu.imt-lille-douai.fr"
resume_contact_telephone:       "06 65 11 23 02"
resume_contact_address:         "29 rue de Carnetin, Dampmart"
resume_header_contact_info: "29 rue de Carnetin, Dampmart | 06 65 11 23 02 | xbroeders@etu.imt-lille-douai.fr"
resume_header_intro: "<p>As a student in my school, I learn to develop in multiple languages (like Python and C), but I also learn a lot by myself.
I can deliver a good quality, clean and working code correctly.
I am comfortable with structured code, and I have good notion in database.<br>
Overall, I like to develop my competences, discover new things and work on it. I am sure that you will find that I learn
fast.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Xylean"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://fr.linkedin.com/in/xyl%C3%A9an-broeders-a571a1159"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://xylean.github.io/resume/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
